### ISSUE TITLE
Script is broken

### ISSUE THREAD

**Issue by snamor** [sergiosusa/github-pr-reviewers#8]
Dear Mantainer:

I seems that the script is broken for the latest version of github. Now the screen to select the users/gropus doesn't even appear.

I'm using the latest version of the script (1.0.1) with Firefox 68.0.1 and GreaseMonkey 4.9.

Thanks for your time and keep up with this great project.

**Comment by xafardero** [comment]
@snamor  and windows :trollface:

**Comment by sergiosusa** [comment]
Dear mr @snamor 

Here the PR that fix the script:
https://github.com/sergiosusa/github-pr-reviewers/pull/9

Thanks to report the issue.

Please check if everything goes right.
